### ISSUE TITLE
javascript 명령어의 하위호환성에 대한 의논.

### ISSUE THREAD

**Issue by wan2land** [Festiv/Bier#4]
```js
I.javascript([
     'bower_components/bxslider-4/dist/jquery.bxslider.js',
     'bower_components/jquery.cookie/jquery.cookie.js',
     'script/main.js'
 ]).to('scripts').concat('main.js');

 I.browserify(['script/admin/**/*.js']).to('admin/js');
```

지금 이렇게 두가지로 구분되어있는데, 굳이 분류를 하자면 `javascript`는 ecma5.1(?) 버전을 다루고, minify 해주는 녀석이고 (필요하면 concat도), `browserify`는 ecma2015를 다루고 minify해주는 녀석인데..

ecma5.1를 ecma2015를 포함하고 있는 듯. 즉, 굳이 저 두가지로 분리할 게 아니고,
`I.javascript`에 `browserify`까지 합치고 `concat`을 계속 지원하도록 하는건 어떨지?

즉, 정리하면..

**1. 예전방식 자바스크립트를 concat을 사용하는 경우.**

```js
I.javascript([ ... ]).concat('main.js').to("dist");
```

**2. 요즘 방식의 ecma2015를 구성하는 경우**

```js
I.javascript([ ... ]).to("dist");
```

**Comment by wan2land** [comment]
concat을 기본 Interface로 제공해서 scss나, copy라던가 등등 모두에서 concat을 제공하는 것도 재밌을 것 같다는 생각.

**Comment by upgle** [comment]
위의 경우도 고려해서 전에 browserify 가 concat 되거나 분리되도록 구현했었는데 사실 browserify 는 CommonJS + Babel 의 개념입니다.
코드 내에서 require('sub modules') 을 사용하면 concat 의 개념이라고 봐도 될텐데 이 경우 concat이 의미가 없어지지 않나요?

**Comment by upgle** [comment]
SCSS 역시도 내부적으로 import를 지원해서 concat이 애매한 경우입니다. 이부분도 고려해볼 필요가 있을것 같습니다.

**Comment by wan2land** [comment]
네. 맞습니다. 모든 것을 require로 하면 가장 좋지만, bower 쪽 스크립트들이 있기 때문에 concat을 버리고 갈 순 없는 것 같습니다. 어차피 concat이 존재해야하고, browserify는 당연히 필요한 상황이면 하나의 인터페이스로 합치면 명령어 갯수를 줄일 수 있어서 좋지 않나라는 생각이 들었습니다.
