### ISSUE TITLE
do 키워드 사용시 경고 메세지 출력

### ISSUE THREAD

**Issue by upgle** [Festiv/Bier#6]
예제에서 사용중인 do 변수명이 phpstorm 에서 아래와 같은 오류가 출력됩니다.
`formal parameter name expected`

**Comment by wan2land** [comment]
잘못된 예제 변수 사용이군요. 어떤 이름을 예시에 쓰는게 가독성이 있을지 고민을 해봐야겠습니다.
원래는 `I`로 했었는데, `do`가 코드 리딩에 도움이 될것 같아서 README만 바꿨는데 그게 화근이었네요.

**Comment by wan2land** [comment]
`I.will.sass()` 이런식도 생각해봤습니다.

**Comment by upgle** [comment]
실제로 실행이 안되네요.. ㅎㅎ
2depth 로 넘어가는것보다는 1depth 로 처리하는게 좋지 않을까요?

**Comment by wan2land** [comment]
당연히 1depth가 좋습니다. :-) 떠올는거 없으면 다시 `I`로 돌려놓을까요.

**Comment by wan2land** [comment]
v0.1.2에서 해결했습니다.
